### ISSUE TITLE
Index prefix should be optional in all commands

### ISSUE THREAD

**Issue by nknguyenhc** [AY2324S1-CS2103T-T08-2/tp#155]

**Comment by Singa-pirate** [comment]
Could you describe this enhancement in more detail? 

I assume you mean that for any command that does not require `/index`, having `/index` in the command should not affect anything. If that's the case, I think it may introduce some confusion for users, for example:

- `create /name 1 /index 10` would actually not create a new contact at index 10
- `delete 1 /index 2` would be valid, yet the meaning is unclear to users

In my opinion, it's better to stick to the NFR that "each valid command should be intuitive such that any new user can understand what it means". LMK if you think otherwise.

**Comment by nknguyenhc** [comment]
When `/index` is missing, the value of index is default to 1. Usually, users might only store one value for each field for each contact (i.e. one phone per person, one email per person, one link per person, etc). I feel that while our current implementation gives the users the flexibility to store multiple values under the same field, it is a downgrade for users that only want to store one value per field.

You may refer to how I implement open link and open email for reference.

**Comment by Singa-pirate** [comment]
Ohh okay, so you mean making `/index` optional when specifying which entry in the list of multi-valued fields, default 1. Can I confirm the only affected commands are `edit` and `delete`?

**Comment by nknguyenhc** [comment]
Yes, should be.
